version: "3"
services:
  mysqldb:
    image: mysql:5.7
    container_name: SQLdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
     
    ports:
      - 3306:3306
  spring-boot:
    depends_on:
     - mysqldb
    image: oussemajerfel/achat-1.0
    restart: always
    ports:
      - 8089:8089
    container_name: fournisseur
